### ISSUE TITLE
Pause on playbar with line in

### ISSUE THREAD

**Issue by kvanisterdael** [duncan3dc/sonos#106]
How can you stop a playbar playing from his Line In? $controller->pause() returns an error: 

 Uncaught duncan3dc\Sonos\Exceptions\SoapException: UPnPError: 701 in /usr/html/phalcon/vendor/duncan3dc/sonos/src/Devices/Device.php:157 Stack trace: #0 /usr/html/phalcon/vendor/duncan3dc/sonos/src/Speaker.php

**Comment by duncan3dc** [comment]
Hi @kvanisterdael, pause is the correct command to stop line in from playing. I've just tried it on my system now and it worked without issue, are you sure the device is still playing when you pause it? Are you sure you are working with the correct device that is currently streaming from line in?

**Comment by christianschneider89** [comment]
Same here. If input is TV this error occurs (I'm using PHP 7.3.15):

PHP Fatal error:  Uncaught duncan3dc\\Sonos\\Exceptions\\SoapException: UPnPError: 701 in /var/www/html/vendor/duncan3dc/sonos/src/Devices/Device.php:157\nStack trace:\n#0 /var/www/html/vendor/duncan3dc/sonos/src/Speaker.php(92): duncan3dc\\Sonos\\Devices\\Device->soap('AVTransport', 'Pause', Array)\n#1 /var/www/html/vendor/duncan3dc/sonos/src/Controller.php(723): duncan3dc\\Sonos\\Speaker->soap('AVTransport', 'Pause', Array)\n#2 /var/www/html/vendor/duncan3dc/sonos/src/Controller.php(189): duncan3dc\\Sonos\\Controller->soap('AVTransport', 'Pause')\n#3 /var/www/html/api.php(31): duncan3dc\\Sonos\\Controller->pause()\n#4 /var/www/html/api.php(171): sonos_stop_all()\n#5 {main}\n  thrown in /var/www/html/vendor/duncan3dc/sonos/src/Devices/Device.php on line 157

The playbar has:
Sonos OS: S2
Version: 12.0.1 (Build 58178090)
Hardwareversion: 1.9.1.10-2.2
Serien-ID: A100

Chris

**Comment by duncan3dc** [comment]
Hmm, I wonder if the playbar works with line-in differently to other speakers, I don't have one so it's going to be tricky to solve for me.
But let me poke around my system now I'm on S2 and see if I can find any line-in issues

**Comment by christianschneider89** [comment]
> I don't have one so it's going to be tricky to solve for me.

If it helps I can set up a linux host in my network for you.
