### ISSUE TITLE
UPnPError: 710 on getFavouriteStations

### ISSUE THREAD

**Issue by zoic21** [duncan3dc/sonos#40]
Hi,
This issue I can reproduced it when I want (not like the other). It's occur when I call getFavouriteStations I alway get UPnPError: 710. Here the log : 

````
[2015-11-04 21:21:42] sonos_debug.INFO: creating speaker instances [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting device info from cache [] []
[2015-11-04 21:21:42] sonos_debug.NOTICE: Getting topology info from: http://192.168.0.30:1400/status/topology [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting xml from cache: http://192.168.0.30:1400/xml/device_description.xml [] []
[2015-11-04 21:21:42] sonos_debug.DEBUG: 192.168.0.30 model: ZP90 [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting xml from cache: http://192.168.0.30:1400/xml/device_description.xml [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting xml from cache: http://192.168.0.128:1400/xml/device_description.xml [] []
[2015-11-04 21:21:42] sonos_debug.DEBUG: 192.168.0.128 model: S1 [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting xml from cache: http://192.168.0.128:1400/xml/device_description.xml [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting xml from cache: http://192.168.0.168:1400/xml/device_description.xml [] []
[2015-11-04 21:21:42] sonos_debug.DEBUG: 192.168.0.168 model: S5 [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting xml from cache: http://192.168.0.168:1400/xml/device_description.xml [] []
[2015-11-04 21:21:42] sonos_debug.INFO: getting xml from cache: http://192.168.0.30:1400/status/topology [] []
[2015-11-04 21:21:42] sonos_debug.INFO: sending soap request to: http://192.168.0.30:1400/MediaServer/ContentDirectory/Control {"ObjectID":"R:0/301","BrowseFlag":"BrowseDirectChildren","Filter":"*","StartingIndex":0,"RequestedCount":100,"SortCriteria":""} []
`````

And the error detail : 
`````
2015/11/04 21:32:44 [error] 13560#0: *45317 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'duncan3dc\Sonos\Exceptions\SoapException' with message 'UPnPError: 710' in /usr/share/nginx/www/jeedom/plugins/sonos3/vendor/duncan3dc/sonos/src/Device.php:134
Stack trace:
#0 /usr/share/nginx/www/jeedom/plugins/sonos3/vendor/duncan3dc/sonos/src/Speaker.php(88): duncan3dc\Sonos\Device->soap('ContentDirector...', 'Browse', Array)
#1 /usr/share/nginx/www/jeedom/plugins/sonos3/vendor/duncan3dc/sonos/src/Services/Radio.php(59): duncan3dc\Sonos\Speaker->soap('ContentDirector...', 'Browse', Array)
#2 /usr/share/nginx/www/jeedom/plugins/sonos3/vendor/duncan3dc/sonos/src/Services/Radio.php(80): duncan3dc\Sonos\Services\Radio->getFavourites(301)
#3 /usr/share/nginx/www/jeedom/test.php(5): duncan3dc\Sonos\Services\Radio->getFavouriteStations()
#4 {main}
  thrown in /usr/share/nginx/www/jeedom/plugins/sonos3/vendor/duncan3dc/sonos/src/Device.php on line 134" while reading response header from upstream, client: 192.168.0.140, server: , request: "GET /test.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "**************"
````

Maybe I do somethink wrong on use of it function bug before 1.5 I remember it's work.

THank in advance

**Comment by duncan3dc** [comment]
Sorry about that, this is fixed in 1.7.3 now
