### ISSUE TITLE
'Failed to lookup the topology info for this speaker'

### ISSUE THREAD

**Issue by kicks66** [duncan3dc/sonos#73]
Using the code:

```
require('vendor/autoload.php');

$sonos = new \duncan3dc\Sonos\Network;
$speakers = $sonos->getSpeakers();
```

I am receiving the following error:

`Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to lookup the topology info for this speaker' in /Users/xxxx/Documents/yyyy/zzzz/vendor/duncan3dc/sonos/src/Network.php:297 Stack trace: #0 /Users/xxxx/Documents/yyyy/zzzz/sonos.php(10): duncan3dc\Sonos\Network->getSpeakers() #1 {main} thrown in /Users/xxxx/Documents/yyyy/zzzz/vendor/duncan3dc/sonos/src/Network.php on line 297`

I am in an office, so potentially an issue with a firewall on a router? Is there a workaround to fix this?

**Comment by duncan3dc** [comment]
Hi @kicks66, sorry you're having problems. Could you enable [logging](http://duncan3dc.github.io/sonos/logging/) and provide the log file for the error?

**Comment by kicks66** [comment]
Thanks for the quick response. Heres the output:

`Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/xxxx/Documents/yyyy/zzzz/vendor/monolog/monolog/src/Monolog/Logger.php on line 311
[2017-08-24 11:00:22] sonos.INFO: creating speaker instances [] []
[2017-08-24 11:00:22] sonos.INFO: discovering devices... [] []
[2017-08-24 11:00:22] sonos.DEBUG: M-SEARCH * HTTP/1.1 HOST: 239.255.255.250:reservedSSDPport MAN: ssdp:discover MX: 1 ST: urn:schemas-upnp-org:device:ZonePlayer:1  [] []
[2017-08-24 11:00:24] sonos.DEBUG: HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://10.2.213.131:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/36.4-42130 (ZPS12) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_949F3E7A45D001400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_sKOlBUPysPulrY1DeFhkqf8Jzl X-RINCON-BOOTSEQ: 6 X-RINCON-WIFIMODE: 1 X-RINCON-VARIANT: 1  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://10.2.219.162:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/36.4-42130 (ZPS1) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_5CAAFD976FDA01400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_g8wFZI5cPeQyahQ8KlbknneXDR X-RINCON-BOOTSEQ: 21 X-RINCON-WIFIMODE: 1 X-RINCON-VARIANT: 0  HTTP/1.1 200 OK CACHE-CONTROL: max-age = 1800 EXT: LOCATION: http://10.2.219.161:1400/xml/device_description.xml SERVER: Linux UPnP/1.0 Sonos/36.4-42130 (ZPS1) ST: urn:schemas-upnp-org:device:ZonePlayer:1 USN: uuid:RINCON_5CAAFD290B5401400::urn:schemas-upnp-org:device:ZonePlayer:1 X-RINCON-HOUSEHOLD: Sonos_g8wFZI5cPeQyahQ8KlbknneXDR X-RINCON-BOOTSEQ: 20 X-RINCON-WIFIMODE: 1 X-RINCON-VARIANT: 0   [] []
[2017-08-24 11:00:24] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://10.2.213.131:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/36.4-42130 (ZPS12)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_949F3E7A45D001400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_sKOlBUPysPulrY1DeFhkqf8Jzl","x-rincon-bootseq":"6","x-rincon-wifimode":"1","x-rincon-variant":"1"} []
[2017-08-24 11:00:24] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://10.2.219.162:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/36.4-42130 (ZPS1)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_5CAAFD976FDA01400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_g8wFZI5cPeQyahQ8KlbknneXDR","x-rincon-bootseq":"21","x-rincon-wifimode":"1","x-rincon-variant":"0"} []
[2017-08-24 11:00:24] sonos.INFO: found device: {usn} {"cache-control":"max-age = 1800","ext":"","location":"http://10.2.219.161:1400/xml/device_description.xml","server":"Linux UPnP/1.0 Sonos/36.4-42130 (ZPS1)","st":"urn:schemas-upnp-org:device:ZonePlayer:1","usn":"uuid:RINCON_5CAAFD290B5401400::urn:schemas-upnp-org:device:ZonePlayer:1","x-rincon-household":"Sonos_g8wFZI5cPeQyahQ8KlbknneXDR","x-rincon-bootseq":"20","x-rincon-wifimode":"1","x-rincon-variant":"0"} []
[2017-08-24 11:00:24] sonos.NOTICE: Getting topology info from: http://10.2.213.131:1400/status/topology [] []
[2017-08-24 11:00:24] sonos.NOTICE: requesting xml from: http://10.2.213.131:1400/xml/device_description.xml [] []
[2017-08-24 11:00:24] sonos.DEBUG: 10.2.213.131 model: S12 [] []
[2017-08-24 11:00:24] sonos.INFO: getting xml from cache: http://10.2.213.131:1400/xml/device_description.xml [] []
[2017-08-24 11:00:24] sonos.NOTICE: requesting xml from: http://10.2.219.162:1400/xml/device_description.xml [] []
[2017-08-24 11:00:24] sonos.DEBUG: 10.2.219.162 model: S1 [] []
[2017-08-24 11:00:24] sonos.INFO: getting xml from cache: http://10.2.219.162:1400/xml/device_description.xml [] []

Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to lookup the topology info for this speaker' in /Users/xxxx/Documents/yyyy/zzzz/vendor/duncan3dc/sonos/src/Network.php:297
Stack trace:
#0 /Users/xxxx/Documents/yyyy/zzzz/vendor/duncan3dc/sonos/src/Network.php(347): duncan3dc\Sonos\Network->getSpeakers()
#1 /Users/xxxx/Documents/yyyy/zzzz/sonos.php(17): duncan3dc\Sonos\Network->getSpeakerByRoom('Living Room')
#2 {main}
  thrown in /Users/xxxx/Documents/yyyy/zzzz/vendor/duncan3dc/sonos/src/Network.php on line 297
`

**Comment by kicks66** [comment]
Hi @duncan3dc any ideas on the above issues?

**Comment by duncan3dc** [comment]
Hi @kicks66, sorry I've not had chance to dig into your logs yet.
At a glance it looks like you have 2 Play:1s, are they are a stereo pair?

**Comment by kicks66** [comment]
We currently have 3 Play:1s working together as a trio.

**Comment by duncan3dc** [comment]
It looks like one your speakers has a different household ID, was it originally used as part of a different system and now you've added it to yours? Do all 3 speakers work correctly using the official Sonos app?

**Comment by duncan3dc** [comment]
I presume you resolved your issue, but feel free to comment and I'll re-open the issue
